"""interaccion_quiz

Revision ID: 5e11a9cf4a0b
Revises: 8010505ef66e
Create Date: 2026-08-12 16:51:39.727323
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5e11a9cf4a0b'
down_revision: str | None = '8010505ef66e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaccion_quiz',
    sa.Column('id_interaccion', sa.Integer(), nullable=False),
    sa.Column('id_capsula', sa.Integer(), nullable=False),
    sa.Column('alternativa_seleccionada', sa.SmallInteger(), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_capsula'], ['microcapsula_generada.id_capsula'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_interaccion')
    )
    op.create_index(op.f('ix_interaccion_quiz_id_capsula'), 'interaccion_quiz', ['id_capsula'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_interaccion_quiz_id_capsula'), table_name='interaccion_quiz')
    op.drop_table('interaccion_quiz')
    # ### end Alembic commands ###
