"""Fase 1: 8 entidades del modelo logico (cap. 17)

Revision ID: ec6446cc3c52
Revises: 
Create Date: 2026-08-06 20:57:30.381250
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ec6446cc3c52'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_fuente',
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('tipo_documento', sa.String(length=40), nullable=True),
    sa.Column('formato', sa.String(length=20), nullable=True),
    sa.Column('origen', sa.String(length=100), nullable=True),
    sa.Column('asignatura', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=True),
    sa.Column('hash_archivo', sa.String(length=128), nullable=True),
    sa.Column('estado_curacion', sa.String(length=30), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado_curacion IN ('pendiente', 'validado', 'rechazado')", name='ck_documento_estado_curacion'),
    sa.PrimaryKeyConstraint('id_documento'),
    sa.UniqueConstraint('hash_archivo')
    )
    op.create_index(op.f('ix_documento_fuente_asignatura'), 'documento_fuente', ['asignatura'], unique=False)
    op.create_table('estudiante',
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('rango_etario', sa.String(length=20), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('carrera', sa.String(length=80), nullable=True),
    sa.Column('ano_ingreso', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_estudiante')
    )
    op.create_index(op.f('ix_estudiante_carrera'), 'estudiante', ['carrera'], unique=False)
    op.create_table('objetivo_aprendizaje',
    sa.Column('id_objetivo', sa.Integer(), nullable=False),
    sa.Column('codigo_objetivo', sa.String(length=30), nullable=False),
    sa.Column('asignatura', sa.String(length=100), nullable=False),
    sa.Column('unidad', sa.String(length=100), nullable=False),
    sa.Column('tema', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivel_taxonomico', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.CheckConstraint("estado IN ('activo', 'inactivo', 'en_revision')", name='ck_objetivo_estado'),
    sa.PrimaryKeyConstraint('id_objetivo'),
    sa.UniqueConstraint('codigo_objetivo')
    )
    op.create_index('ix_objetivo_asignatura_unidad', 'objetivo_aprendizaje', ['asignatura', 'unidad'], unique=False)
    op.create_table('diagnostico_vark',
    sa.Column('id_diagnostico', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('puntaje_v', sa.Integer(), nullable=False),
    sa.Column('puntaje_a', sa.Integer(), nullable=False),
    sa.Column('puntaje_r', sa.Integer(), nullable=False),
    sa.Column('puntaje_k', sa.Integer(), nullable=False),
    sa.Column('porcentaje_v', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('porcentaje_a', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('porcentaje_r', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('porcentaje_k', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_diagnostico', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('porcentaje_v + porcentaje_a + porcentaje_r + porcentaje_k BETWEEN 99.95 AND 100.05', name='ck_diagnostico_porcentajes_suman_100'),
    sa.CheckConstraint('puntaje_v >= 0 AND puntaje_a >= 0 AND puntaje_r >= 0 AND puntaje_k >= 0', name='ck_diagnostico_puntajes_no_negativos'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_diagnostico')
    )
    op.create_index(op.f('ix_diagnostico_vark_id_estudiante'), 'diagnostico_vark', ['id_estudiante'], unique=False)
    op.create_table('fragmento',
    sa.Column('id_fragmento', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('id_objetivo', sa.Integer(), nullable=True),
    sa.Column('numero_fragmento', sa.Integer(), nullable=False),
    sa.Column('tipo_fragmento', sa.String(length=30), nullable=False),
    sa.Column('contenido_texto', sa.Text(), nullable=True),
    sa.Column('ruta_recurso', sa.String(length=255), nullable=True),
    sa.Column('pagina_inicio', sa.Integer(), nullable=True),
    sa.Column('pagina_fin', sa.Integer(), nullable=True),
    sa.Column('etiqueta_tematica', sa.String(length=100), nullable=True),
    sa.Column('metadatos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado_validacion', sa.String(length=30), nullable=False),
    sa.CheckConstraint("estado_validacion IN ('pendiente', 'validado', 'descartado')", name='ck_fragmento_estado_validacion'),
    sa.CheckConstraint('pagina_fin IS NULL OR pagina_inicio IS NULL OR pagina_fin >= pagina_inicio', name='ck_fragmento_paginas_coherentes'),
    sa.ForeignKeyConstraint(['id_documento'], ['documento_fuente.id_documento'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_objetivo'], ['objetivo_aprendizaje.id_objetivo'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_fragmento'),
    sa.UniqueConstraint('id_documento', 'numero_fragmento', name='uq_fragmento_documento_numero')
    )
    op.create_index(op.f('ix_fragmento_id_documento'), 'fragmento', ['id_documento'], unique=False)
    op.create_index('ix_fragmento_objetivo_estado', 'fragmento', ['id_objetivo', 'estado_validacion'], unique=False)
    # Índice GIN para el full-text search en español (filtro secundario del
    # retriever, Fase 2). Escrito a mano: el autogenerate de Alembic no emite
    # los índices definidos por expresión, así que si se regenera esta
    # migración hay que volver a agregarlo.
    op.create_index(
        'ix_fragmento_contenido_fts',
        'fragmento',
        [sa.text("to_tsvector('spanish', contenido_texto)")],
        unique=False,
        postgresql_using='gin',
    )
    op.create_table('configuracion_contenido',
    sa.Column('id_config', sa.Integer(), nullable=False),
    sa.Column('id_diagnostico', sa.Integer(), nullable=False),
    sa.Column('peso_texto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('peso_visual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('peso_narrativo', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('peso_practico', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recursos_visuales', sa.SmallInteger(), nullable=False),
    sa.Column('palabras_texto', sa.SmallInteger(), nullable=False),
    sa.Column('componentes_practicos', sa.SmallInteger(), nullable=False),
    sa.Column('audio_activo', sa.Boolean(), nullable=False),
    sa.Column('tono_narrativo', sa.String(length=20), nullable=False),
    sa.Column('canales_activos', sa.String(length=10), nullable=False),
    sa.CheckConstraint('palabras_texto BETWEEN 150 AND 300', name='ck_config_palabras_150_300'),
    sa.CheckConstraint('recursos_visuales >= 0 AND componentes_practicos >= 0', name='ck_config_cantidades_no_negativas'),
    sa.ForeignKeyConstraint(['id_diagnostico'], ['diagnostico_vark.id_diagnostico'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_config'),
    sa.UniqueConstraint('id_diagnostico')
    )
    op.create_table('respuesta_vark',
    sa.Column('id_respuesta', sa.Integer(), nullable=False),
    sa.Column('id_diagnostico', sa.Integer(), nullable=False),
    sa.Column('num_pregunta', sa.SmallInteger(), nullable=False),
    sa.Column('alternativa', sa.String(length=1), nullable=False),
    sa.Column('canal_mapeado', sa.String(length=1), nullable=False),
    sa.CheckConstraint("canal_mapeado IN ('V', 'A', 'R', 'K')", name='ck_respuesta_canal_vark'),
    sa.CheckConstraint('num_pregunta BETWEEN 1 AND 16', name='ck_respuesta_num_pregunta_1_16'),
    sa.ForeignKeyConstraint(['id_diagnostico'], ['diagnostico_vark.id_diagnostico'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_respuesta'),
    sa.UniqueConstraint('id_diagnostico', 'num_pregunta', 'alternativa', name='uq_respuesta_diagnostico_pregunta_alternativa')
    )
    op.create_index(op.f('ix_respuesta_vark_id_diagnostico'), 'respuesta_vark', ['id_diagnostico'], unique=False)
    op.create_table('microcapsula_generada',
    sa.Column('id_capsula', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_objetivo', sa.Integer(), nullable=False),
    sa.Column('id_config', sa.Integer(), nullable=True),
    sa.Column('id_fragmento_fuente', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('contenido_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mini_quiz_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado_validacion', sa.String(length=30), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado_validacion IN ('generada', 'validada', 'rechazada')", name='ck_capsula_estado_validacion'),
    sa.ForeignKeyConstraint(['id_config'], ['configuracion_contenido.id_config'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_fragmento_fuente'], ['fragmento.id_fragmento'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_objetivo'], ['objetivo_aprendizaje.id_objetivo'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_capsula')
    )
    op.create_index('ix_capsula_estudiante_objetivo', 'microcapsula_generada', ['id_estudiante', 'id_objetivo'], unique=False)
    op.create_index(op.f('ix_microcapsula_generada_id_estudiante'), 'microcapsula_generada', ['id_estudiante'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_microcapsula_generada_id_estudiante'), table_name='microcapsula_generada')
    op.drop_index('ix_capsula_estudiante_objetivo', table_name='microcapsula_generada')
    op.drop_table('microcapsula_generada')
    op.drop_index(op.f('ix_respuesta_vark_id_diagnostico'), table_name='respuesta_vark')
    op.drop_table('respuesta_vark')
    op.drop_table('configuracion_contenido')
    op.drop_index('ix_fragmento_contenido_fts', table_name='fragmento')
    op.drop_index('ix_fragmento_objetivo_estado', table_name='fragmento')
    op.drop_index(op.f('ix_fragmento_id_documento'), table_name='fragmento')
    op.drop_table('fragmento')
    op.drop_index(op.f('ix_diagnostico_vark_id_estudiante'), table_name='diagnostico_vark')
    op.drop_table('diagnostico_vark')
    op.drop_index('ix_objetivo_asignatura_unidad', table_name='objetivo_aprendizaje')
    op.drop_table('objetivo_aprendizaje')
    op.drop_index(op.f('ix_estudiante_carrera'), table_name='estudiante')
    op.drop_table('estudiante')
    op.drop_index(op.f('ix_documento_fuente_asignatura'), table_name='documento_fuente')
    op.drop_table('documento_fuente')
    # ### end Alembic commands ###
